project_name: template
release:
  github:
    owner: dihedron
    name: template
  name_template: '{{.Tag}}'
scoop:
  name: template
  commit_author:
    name: Andrea Funtò
    email: dihedron.dev@gmail.com
  commit_msg_template: Scoop update for {{ .ProjectName }} version {{ .Tag }}
before:
  hooks:
#    - make clean
    - go mod tidy
    - go generate ./...
builds:
  - env: 
    - DESCRIPTION=Golang template engine
    - COPYRIGHT=2023 © Andrea Funtò
    - LICENSE=MIT
    - LICENSE_URL=https://opensource.org/licenses/MIT
    - GOVERSION=$(go version | awk '{print $3;}' | sed 's/^go//')
    - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    flags:
      - -v
    hooks:
    #   pre: <whatever>
      # post: 
      #   - upx --best "{{.Path}}"
nfpms:
- maintainer: Andrea Funtò <dihedron dot dev at gmail dot com>
  description: Golang template engine.
  homepage: https://github.com/dihedron/template
  license: MIT
  formats:
  - deb
  - rpm
  - apk
#archives:
#  - replacements:
#      darwin: Darwin
#      linux: Linux
#      windows: Windows
#      386: i386
#     amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# gomod:
#   proxy: false
#   env:
#     - GOPROXY=https://proxy.golang.org,direct
#     - GOSUMDB=sum.golang.org
#     - GOPRIVATE=example.com/blah
#  gobinary: go




